// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: rpc/cache/service.proto

package cache

import context "context"
import fmt "fmt"
import io "io"
import ioutil "io/ioutil"
import http "net/http"
import strings "strings"

import twirp "github.com/twitchtv/twirp"

const (
	// CacheServicePathPrefix is the path prefix for Twirp RPC calls.
	CacheServicePathPrefix = "/twirp/trivy.rpc.cache.CacheService/"
)

// CacheService is the trivy cache service.
//
// The trivy cache service provides RPCs for caching and retrieving scan results.
//
//go:generate protoc --twirp_out=. --go_out=. rpc/cache/service.proto
//
// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: rpc/cache/service.proto

type CacheService interface {
	Get(ctx context.Context, in *GetRequest) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest) (*SetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest) (*DeleteResponse, error)
}

type cacheServiceProtobufClient struct {
	client HTTPClient
	urls   [3]string
}

func NewCacheServiceProtobufClient(baseURL string, client HTTPClient) CacheService {
	baseURL = strings.TrimRight(baseURL, "/")
	return &cacheServiceProtobufClient{
		client: client,
		urls: [3]string{
			baseURL + CacheServicePathPrefix + "Get",
			baseURL + CacheServicePathPrefix + "Set",
			baseURL + CacheServicePathPrefix + "Delete",
		},
	}
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequestWithContext(ctx, "POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Accept", contentType)
	return req, nil
}

// ... (rest of generated file unchanged)
